// The manual, written as the Pilot's Notes a squadron issued: what each
// part of the game is for, the controls, and how to fly and fight it.
//
// Markup, one paragraph per string:
//   '# Heading'          a heading
//   '- text'             a bullet
//   'KEY | what it does' a two-column row (keys, controls)
//   anything else        a paragraph

export interface ManualChapter {
  title: string;
  body: string[];
}

export const MANUAL: ManualChapter[] = [
  {
    title: 'GETTING STARTED',
    body: [
      'Summer 1940. You fly a Hurricane or a Spitfire with an RAF squadron in 11 Group, defending the south-east of England. These notes cover the controls, flying and fighting, and the campaign.',
      '# FROM THE MAIN MENU',
      'CAMPAIGN 1940 | July to October as one pilot. You start as a Pilot Officer flying as a wingman. Promotion, losses and postings follow.',
      'SCRAMBLE! | A single sortie on a random day of the battle, from readiness at a random station.',
      'QUICK COMBAT | Straight into the air near a raid: pick your aircraft, the raid, the escort, the weather and who flies with you.',
      'THE OTHER SIDE | Fly a Bf 109 escorting bombers over England, and get home across the Channel on what fuel you have left.',
      'LOGBOOK | Every sortie you have flown, in your own hand.',
      'SETTINGS | How hard the game is, and how it looks and sounds.',
      '# THREE WAYS TO PLAY',
      'Set in SETTINGS, under MODE:',
      'ARCADE | A faster, tougher aircraft that will not spin or black you out. JUMP TO RAID takes you to the fight once you are airborne. AIR START begins in the air by the raid.',
      'ASSIST | The real aircraft with a helping hand: one START button, the docking computer to bring you home, and help with landing.',
      'AUTHENTIC | Everything by hand.',
      'ENEMY sets how good the Germans are, from FLIGHT SCHOOL to SPAIN VETERANS.',
    ],
  },
  {
    title: 'KEYBOARD',
    body: [
      '# FLYING',
      'ARROWS / WASD | Stick: back is nose up',
      'Z  X | Rudder',
      '+  - | Throttle',
      'E | Boost (emergency power, limited)',
      'SPACE | Fire',
      'G | Undercarriage (hold to pump it up in a Spitfire)',
      'F | Flaps',
      ', | Wheel brakes (hold)',
      'U | Fly with the mouse on or off',
      '# THE SORTIE',
      'I | Start up: each press does the next step',
      'Q | The R/T menu; then 1 to 6 for a call',
      'T | Tally-ho: you have the enemy in sight',
      '1 2 3 4 | Orders when leading: bombers, escort, follow me, re-form',
      'V | Ask for a homing',
      'N | Jump home (Assist, after a homing)',
      'R | Jump to the raid (Arcade, after taking off)',
      'O | Engine off, once down and stopped after landing',
      'J | Bail out',
      'C | Canopy',
      '# LOOKING ABOUT',
      'P | Padlock the nearest enemy (the view follows him)',
      'B | Look back (hold)',
      'F1 | Cockpit views, in turn',
      'F2  F3  F4 | Padlock, chase and fly-by views',
      'K | Full or slim instrument panel',
      'M | The map',
      '[  ] | Time compression down and up (x1 to x8)',
      'ESC | Pause',
    ],
  },
  {
    title: 'TOUCH AND GAMEPAD',
    body: [
      '# TOUCH SCREEN',
      '- Left of the screen: the stick. Put your thumb down anywhere and move it; let go and the stick centres.',
      '- Right of the screen: the throttle slider and the FIRE button, with PADLOCK, LOOK BACK, R/T, VIEW, MAP and pause beside them.',
      '- Top left: buttons for what you can do right now, such as GEAR, FLAPS, BOOST, TIME, HOMING, orders when leading, and BAIL OUT. They change as the sortie goes on.',
      '- TILT CONTROL (in SETTINGS) flies by tilting the phone. Calibrate it from the pause menu holding the phone as you will fly.',
      '- Save the page to your home screen to play full screen, offline. It updates itself when opened online.',
      '# GAMEPAD',
      'LEFT STICK | Stick',
      'RIGHT STICK | Rudder (left and right), throttle (up and down)',
      'D-PAD | Throttle up and down; time compression left and right',
      'RT / RB | Fire',
      'LT | Look back',
      'A | Tally-ho (OK in menus)',
      'B | Padlock (back in menus)',
      'X | Undercarriage (hold to pump)',
      'Y | Flaps',
      'LB | Views',
      'L3 | Boost',
      'R3 | Start up',
      'BACK | Map',
      'START | Pause',
    ],
  },
  {
    title: 'STARTING UP',
    body: [
      'From readiness the phone rings, and you run for the aircraft. Before it rings you can set your guns\' convergence, read the weather board and the intelligence report.',
      '# THE ENGINE',
      'The fitter tells you how many strokes of the primer she wants: three on a summer afternoon, more on a cold morning.',
      '- PRIMER: one stroke a press. Give her what the fitter said. One stroke short and she will probably cough and die; too many and she floods.',
      '- MAGS: magnetos on.',
      '- STARTER: turn her over. Primed right she usually catches, but not always: try again.',
      '- Flooded? Keep turning her over on the starter. That blows out the extra fuel.',
      'The start-up panel shows the strokes, the magnetos and the starter, with an arrow on the next step. With Assist on, START does it all.',
      '# TAKING OFF',
      '- Taxi with the throttle and rudder. Brakes are on the comma key.',
      '- Open up smoothly. The torque swings the nose; keep it straight with rudder (auto-rudder does it for you).',
      '- She flies at about 80 mph. Undercarriage up, and climb at 160 to 180 mph.',
      '- The Spitfire\'s undercarriage comes up by hand pump: keep pumping (hold G) until the lights change.',
    ],
  },
  {
    title: 'FLYING HER',
    body: [
      '# HANDS OFF',
      'Let go of the stick and she holds the line you were on, as if trimmed: level, a climb or a gentle dive. Let go near wings-level and she rolls gently level; let go in a turn and she holds the bank. Time compression is safe in the cruise, and drops back to x1 by itself when the enemy is near.',
      '# THE STALL',
      'Pull too hard or fly too slow and the wing stalls. The buffet (shaking) warns you first. Ease the stick forward. Pulling hard in a stall with rudder on spins her: stick forward and opposite rudder to recover, and you need height for it. STALL GUARD (in SETTINGS) holds the wing at the buffet when you haul back.',
      '# POWER',
      '- BOOST is emergency power: faster and climbs better, but use it for five minutes at most or the engine overheats.',
      '- Watch the radiator temperature, low and slow, or with a holed radiator. Throttle back and keep the speed up to cool her.',
      '- The Merlin\'s carburettor cuts out under negative g: push the nose down hard and the engine coughs. The 109 has fuel injection and does not. Roll and pull into a dive instead of pushing.',
      '# G',
      'Pull hard for long and you grey out, then black out. Ease off and the sight comes back.',
      '# THE AIRCRAFT',
      'HURRICANE | Rugged and steady, turns well, a good gun platform. Slower.',
      'SPITFIRE | Faster, climbs better, turns tighter still, lighter on the controls.',
      'BF 109 | Fast in the climb and dive, cannon. Its elevator goes heavy at speed, so it pulls out of a fast dive slowly. Short on fuel over England.',
    ],
  },
  {
    title: 'FINDING THE ENEMY',
    body: [
      '# THE CONTROLLER',
      'The sector controller sends you after a raid: a vector (course), angels (height in thousands of feet) and what to expect. Heights and numbers from the radar are often well out. Climb above where he says if you can, and come out of the sun.',
      '# THE R/T MENU',
      'Press R/T (Q) for the calls that fit the moment:',
      '- VECTOR: the course to your raid again.',
      '- NEW RAID: another raid if yours is gone.',
      '- FIX: where you are, and the way to the nearest field.',
      '- SEND HELP: another squadron against a big raid.',
      '- RTB: tell him you are breaking off, damaged, out of ammunition or short of fuel.',
      '- MAYDAY: going down. Over the sea it brings air-sea rescue.',
      '# THE MAP',
      'M opens the ops-room plot. It is renewed every 30 seconds, with errors, like the real one.',
      '- Red counters: hostiles. Strength ("17+") and height ("A15" for 15,000 ft). A raid in sight splits into its groups: bombers, escort, stragglers.',
      '- Blue counters: other squadrons of ours, with a dotted line to the raid they have been sent after. A big wing is one counter.',
      '- Black counters: going home.',
      '- You: the flashing dot. With Assist, the ring shows how far you could glide.',
      '# SEEING THEM',
      'Specks first, then shapes. Markers (if on in SETTINGS) show the raid you were sent after, and anything close. PADLOCK (P) holds your view on the nearest enemy. Look behind often (B): the 109s come down out of the sun.',
    ],
  },
  {
    title: 'COMBAT',
    body: [
      '# YOUR GUNS',
      'Eight Brownings, about 15 seconds of fire. They are harmonised to meet at the convergence you set at dispersal (250, 300 or 400 yards). Get close: at 250 yards or less every hit counts. A lucky hit at long range is possible but rare.',
      '- Aim ahead of a crossing target: lead him by the gunsight\'s rings.',
      '- Short bursts. Watch the ammunition.',
      '# BOMBERS',
      'The formation\'s gunners cover each other. Attack from the beam or head-on, break away below, and do not sit behind a bomber for long. Bombers under attack straggle, jettison their bombs and turn for home.',
      '# FIGHTERS',
      '- The 109 is fast in the dive and climb. He likes to dive on you, fire and zoom away. Do not follow him down.',
      '- You out-turn him, especially in a Spitfire, and his elevator goes heavy at speed. If he is behind you, break hard into him.',
      '- Escorts that see you attacking the bombers will come for you.',
      '# LEADING',
      'As a Flight Lieutenant or Squadron Leader you lead. Once engaged, give orders with 1 to 4 (or the buttons): BOMBERS, ESCORT, FOLLOW (stay with me), RE-FORM.',
      '# CLAIMS',
      'The intelligence officer allows your claims as destroyed, probable or damaged, depending on what was seen. Witnesses help.',
    ],
  },
  {
    title: 'DAMAGE AND GETTING HOME',
    body: [
      '# HIT',
      '- GLYCOL: white smoke, and the temperature climbs. Throttle back, keep your speed, and head for home before she seizes.',
      '- OIL: on the windscreen, and the engine will not last.',
      '- FIRE: get out. The BAIL OUT button counts down the seconds you have.',
      '- Shot-up controls are heavy and the aircraft pulls to one side.',
      '- Wounded: the screen edges pulse red and the controls are slow.',
      '# BAILING OUT',
      'J, or BAIL OUT, above about 400 ft. Over England you will be back on the squadron; over the sea you need rescuing; over France you are a prisoner.',
      '# HOME',
      '- HOMING (V): the controller gives you the course and distance to the nearest field.',
      '- JUMP HOME (Assist): straight onto final approach for that field; move the stick to take over, or let the docking computer land her.',
      '- Out of fuel or the engine gone: glide (the map\'s ring shows how far) and put down in a field, wheels up if it is rough. Put a sound aircraft down in a field and you will be written up.',
      '# LANDING',
      'Undercarriage down, flaps down once below about 160 mph, come in at about 90 mph, and hold off just above the grass. With Assist, the approach aids show the way in. Down and stopped, ENGINE OFF (O) finishes the sortie.',
    ],
  },
  {
    title: 'CAMPAIGN 1940',
    body: [
      'One pilot from 10 July to the end of October. Only the big days are flown; the days between pass off the screen, with losses, claims and replacements. Being shot down is not the end (you fly the sortie again) unless IRONMAN is on.',
      '# THE BOARD',
      'In the dispersal hut: the date and the phase of the battle, you, the squadron, the sector stations, and the news.',
      '- TO DISPERSAL: fly today\'s next sortie.',
      '- FORMATION: tight vics, or looser pairs once the squadron can (from mid-August). Pairs lose fewer pilots.',
      '- The airfield line: the field the squadron flies from (see below).',
      '- POSTINGS: ask for a move (see below).',
      '- THE SQUADRON: the pilots, their sorties, claims, fatigue and state.',
      '# RANK',
      'Fly sorties and score, and you are promoted: Flight Lieutenant with a flight to lead, then Squadron Leader with the squadron. Losses among the leaders can promote you sooner. Being written up holds you back.',
      '# FATIGUE',
      'Every sortie tires you and the others. Nights off bring it down. Tired pilots are stood down.',
      '# EXPERIENCE ON TYPE',
      'Your hours on each type count: GREEN, then NEW (20 hrs), FAMILIAR (35) and SKILLED (55). A skilled pilot gets a little more from the controls, is less likely to spin, nurses a damaged aircraft home better and uses less fuel. A green one is a little worse.',
      '# WHERE YOU FLY FROM',
      'Each sector station has satellite and forward fields: Biggin Hill has Hawkinge, Lympne, West Malling and Gravesend; Hornchurch has Manston and Rochford; and so on. Forward fields are much nearer the raids, but you are caught on the ground more often. If your station is bombed out, the squadron moves to a satellite until it reopens.',
      '# POSTINGS',
      '- Ask Group for a posting to another squadron at any station, on either type. Changing type means three days converting first, and you start GREEN on it. Your rank goes with you.',
      '- As Squadron Leader you can move your own squadron instead.',
      '- Not while you are in hospital, and not within ten days of your last move.',
      '# THE SCORE',
      'At the end: how many days the sector stations stayed open, how many raids were turned back, how many of the squadron survived, your record and your rank.',
    ],
  },
  {
    title: 'SETTINGS',
    body: [
      'MODE | Arcade, Arcade with an air start, Assist or Authentic (see Getting Started).',
      'ENEMY | Flight School, Normal or Spain Veterans.',
      'ENEMY MARKERS | Marks on the raid you were sent after and enemies near you.',
      'BIG SPEED/HEIGHT | Large readouts beside the panel.',
      'AMMO BAR | Rounds left, as a bar (with Assist).',
      'AUTO-RUDDER | Keeps the ball in the middle for you.',
      'STALL GUARD | Full back stick holds the wing at the buffet instead of stalling it.',
      'BIG TARGETS | Enemy aircraft easier to hit.',
      'COMPASS STRIP | A heading strip across the top of the view.',
      'TILT CONTROL | Fly by tilting a phone or tablet.',
      'HAPTICS | Vibration when hit, on phones that have it.',
      '1990 MODE | The frame rate an Amiga would have managed.',
      'SOUND, MUSIC | Volume and music on or off.',
      'PANEL | The full instrument panel, or a slim one for more view.',
      'Auto-rudder, stall guard, big targets, the compass, tilt and the panel can also be changed from the pause menu in flight.',
    ],
  },
];
